# Generated by Django 4.2.8 on 2024-03-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/products'),
        ),
    ]
