# Generated by Django 4.2.8 on 2024-03-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='coutry',
            new_name='country',
        ),
    ]
